org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
org.gradle.daemon=false
org.gradle.caching=true
org.gradle.parallel=true
android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=true
android.defaults.buildfeatures.buildconfig=false
android.aapt2FromMavenOverride=/data/data/com.termux/files/usr/bin/aapt2
