apply plugin: 'com.android.application'

android {
    namespace 'com.fahim.myide'
    compileSdk 34

    defaultConfig {
        applicationId "com.fahim.myide"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        jniLibs {
            useLegacyPackaging = true
        }
        resources {
            excludes += [
                'META-INF/DEPENDENCIES',
                'META-INF/LICENSE',
                'META-INF/LICENSE.txt',
                'META-INF/NOTICE',
                'META-INF/NOTICE.txt',
                'META-INF/*.kotlin_module'
            ]
        }
    }

    androidResources {
        noCompress 'jar', 'zip', 'so', 'dex', 'gz', 'tgz', 'modules', 'dat', 'cfg', 'sym', 'jimage'
    }

    lint {
        abortOnError false
        checkReleaseBuilds false
    }
}

dependencies {
    implementation 'androidx.core:core:1.13.1'
    implementation fileTree(dir: 'libs', include: ['*.jar'])
}
