name: kotlin-compile

on:
  workflow_dispatch:
    inputs:
      payload:
        description: 'payload'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
